# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- django_upgrade_5_node

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  tagDate: $[ format('{0:yyyy}.{0:MM}.{0:dd}.{0:HH}.{0:mm}{0:ss}', pipeline.startTime) ]
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/django_upgrade_5')]
  
stages:
- stage: Build
  condition: and(succeeded(), eq(variables.isMain, 'true'))
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image and Push
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: | 
              latest
              $(tagDate)
        containerRegistry: DockerHub
        repository: dbcawa/wildlifecompliance
    - task: Docker@2
      displayName: Dev Build image and Push
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/dockerdev/Dockerfile'
        tags: | 
              wildlifecompliance_dev_latest
              wildlifecompliance_dev_$(tagDate)              
        containerRegistry: DockerHub
        repository: dbcawa/docker_app_dev       
